chat/chat/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('rooms/', include('room.urls')),
]

chat/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path("", views.frontpage, name="frontpage"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', next_page='room:rooms'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    
]

chat/room/urls.py
from django.urls import path

from . import views


app_name = 'room'

urlpatterns = [
    path('', views.rooms, name='rooms'),
    path('<slug:slug>/', views.room, name='room'),
    
]

chat/core/models.py
from django.db import models

# Create your models here.

chat/room/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    
    def __str__(self):
        return self.name


class Message(models.Model):

    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

chat/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1', 'password2']

chat/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login

from .forms import SignUpForm


def frontpage(request):
    
    return render(request, 'core/frontpage.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            
            login(request, user)
            
            return redirect('frontpage')
        
    else:
        form = SignUpForm()
    
    return render(request, 'core/signup.html', {'form':form})

chat/room/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Room, Message


@login_required
def rooms(request):
    
    rooms = Room.objects.all()
    
    return render(request, 'room/rooms.html', {'rooms':rooms})

@login_required
def room(request, slug):
    
    room = Room.objects.get(slug=slug)
    messages = Message.objects.filter(room=room)[0:30]

    context = {
        'room': room,
        'messages': messages
    }
    
    return render(request, 'room/room.html', context)
    

chat/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock title %} | Chat</title>
    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        .chat-messages{
            height: 400px;
            overflow-y: auto;
        }
    </style>

</head>

<body style="background-color: teal;">
    <nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
        <div>
            <a href="/" class="text-xl text-white">Chat</a>
        </div>

        <div class="flex items-center space-x-4">
            
            {% if request.user.is_authenticated %}
                <a href="/rooms/" class="text-white hover:text-gray-200">Rooms</a>
                <a href="/logout/" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Log out</a>
            {% else %}
                <a href="/login/" class="text-white hover:text-gray-200">Log in</a>
                <a href="/signup/" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Sign up</a>
            {% endif %}
                
        </div>
    </nav>

    
    {% block content %}
        
    {% endblock content %}

    {% block script %}
    {% endblock script %}
        
</body>
</html>

chat/core/templates/core/frontpage.html
{% extends 'core/base.html' %}


{% block title %}
    Welcome
{% endblock title %}
    

{% block content %}
    <div class="p-10 lg:p-20 text-center">
        <h1 class="text-3xl lg:text-6xl text-white">Chat</h1>
    </div>
{% endblock content %}
    

chat/core/templates/core/login.html
{% extends 'core/base.html' %}


{% block title %}
    Log in
{% endblock title %}
    

{% block content %}
    <div class="p-10 lg:p-20 text-center">
        <h1 class="text-3xl lg:text-6xl text-white">Sign in</h1>
    </div>

    <form action="" method="post" class="lg:w-1/4 px-4 mx-auto">
        {% csrf_token %}

        <div class="mb-5">
            <label for="username" class="text-white">Username</label>

            <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
        </div>

        <div class="mb-5">
            <label for="password" class="text-white">Password</label>

            <input type="password" name="password" class="w-full mt-2 px-4 py-2 rounded-xl">
        </div>

        
        {% if form.errors %}
            
            {% for field in form %}
                
                {% for error in field.errors %}
                    <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                        <p>{{ error|escape }}</p>
                    </div>
                {% endfor %}
                    
            {% endfor %}
                            
        {% endif %}
            
        <button class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">Log in</button>

    </form>
{% endblock content %}
    

chat/core/templates/core/signup.html
{% extends 'core/base.html' %}


{% block title %}
    Sign up
{% endblock title %}
    

{% block content %}
    <div class="p-10 lg:p-20 text-center">
        <h1 class="text-3xl lg:text-6xl text-white">Sign up</h1>
    </div>

    <form action="" method="post" class="lg:w-1/4 px-4 mx-auto">
        {% csrf_token %}

        <div class="mb-5">
            <label for="username" class="text-white">Username</label>

            <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
        </div>

        <div class="mb-5">
            <label for="password" class="text-white">Password</label>

            <input type="password" name="password1" class="w-full mt-2 px-4 py-2 rounded-xl">
        </div>

        <div class="mb-5">
            <label for="password2" class="text-white">Repeat password</label>

            <input type="password" name="password2" class="w-full mt-2 px-4 py-2 rounded-xl">
        </div>

        
        {% if form.errors %}
            
            {% for field in form %}
                
                {% for error in field.errors %}
                    <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                        <p>{{ error|escape }}</p>
                    </div>
                {% endfor %}
                    
            {% endfor %}
                            
        {% endif %}
            
        <button class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">Submit</button>

    </form>
{% endblock content %}
    

chat/room/templates/room/room.html
{% extends 'core/base.html' %}


{% block title %}
    {{ room.name }}
{% endblock title %}
    

{% block content %}
    <div class="p-10 lg:p-20 text-center">
        <h1 class="text-3xl lg:text-6xl text-white">{{ room.name }}</h1>
    </div>

    <div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
        <div class="chat-messages space-y-3" id="chat-messages">
            {% for message in messages %}
                <div class="p-4 bg-gray-200 rounded-xl">
                    <p class="font-semibold"> {{ message.user.username }} </p>'
                    <p> {{ message.content }} </p>
                </div>'
            {% endfor %}
        </div>
    </div>

    <div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
        <form action="." method="post" class="flex">
            {% csrf_token %}
            <input type="text" name="content" class="flex-1 mr-3" placeholder="Your message..." id="chat-message-input">
        
            <button class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700" id="chat-message-submit">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

{% block script %}
{{ room.slug|json_script:"json_roomname" }}
{{ request.user.username|json_script:"json_username"}}

    <script>
        const roomName = JSON.parse(document.getElementById('json_roomname').textContent)
        const userName = JSON.parse(document.getElementById('json_username').textContent)

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e){
            console.log('onmessage')

            const data = JSON.parse(e.data);

            if(data.message){
                let html = '<div class="p-4 bg-gray-200 rounded-xl">'
                    html += '<p class="font-semibold">' + data.username + '</p>'
                    html += '<p>'+ data.message +'</p></div>'

                document.querySelector('#chat-messages').innerHTML += html
            
                scrollToBottom()
            }else{
                alert('empty message')
            }
        }

        chatSocket.onclose = function(e){
            console.log('onclose')
        }

        // sending messages
        document.querySelector('#chat-message-submit').onclick = function(e){
            e.preventDefault()
            const messageInputDom = document.querySelector('#chat-message-input')
            const message = messageInputDom.value

            chatSocket.send(JSON.stringify({
                'message': message,
                'username': userName,
                'room': roomName
            }));

            messageInputDom.value = ''

            return false
        }

        // scrool to the bottom
        function scrollToBottom(){
            const objDiv = document.querySelector('#chat-messages')
            objDiv.scrollTop = objDiv.scrollHeight
        }

        scrollToBottom()

    </script>
{% endblock %}
    

chat/room/templates/room/rooms.html
{% extends 'core/base.html' %}


{% block title %}
    Rooms
{% endblock title %}
    

{% block content %}
    <div class="p-10 lg:p-20 text-center">
        <h1 class="text-3xl lg:text-6xl text-white">Rooms</h1>
    </div>

    <div class="w-full flex flex-wrap items-center">
        
        {% for room in rooms %}
            <div class="w-full lg:w-1/4 px-3 py-3">
                <div class="p-4 bg-white shadow rounded-xl text-center">
                    <h2 class="mb-5 text-2xl font-semibold">{{ room.name }}</h2>

                    <a href="{% url 'room:room' room.slug %}" class="px-5 py-3 block rounded-xl text-white bg-teal-600 hover:bg-teal-700">Join</a>
                </div>
            </div>
        {% endfor %}
            
    </div>
{% endblock content %}
    